### ISSUE TITLE
Anyway to save the text file I edited

### ISSUE THREAD

**Issue by kykm1307** [VPKSoft/ScintillaDiff#30]
Anyway to save the text file I edited? because i tried to edit the file I imported in. However when I tried to modify it and save, the text extracted is the original text file instead the modified version.

**Comment by VPKSoft** [comment]
Not at the moment no. The two different texts in the Scintilla controls have already been modified to indicate the changes so the changed text would also contain these place holder characters, etc. Accessing the text should be quite easy though, something like:
```cs
/// <summary>
/// Gets the modified text on the left <see cref="Scintilla"/> scintilla control.
/// </summary>
/// <value>The modified text left <see cref="Scintilla"/> scintilla control.</value>
public string ModifiedTextLeft => scintillaOne.Text;
```

In the _ScintillaDiff\ScintillaDiffControl.cs_ file...

**Comment by kykm1307** [comment]
alright. How about to get text for the particular line. Example I want to get the whole text of line 2 to move from left scintilla to right scintilla?

**Comment by VPKSoft** [comment]
I don't think implementing such feature would be worth the trouble. The `Scintilla.Lines` collection is "virtual" and read-only because one doesn't know the line endings used in a particular text. You can't really assign anything to the lines collection. I.e. the following would lead to an error: `scintilla.Lines[0].Text = "abcd";` Also the line's Text property contains the line ending making this to set an identical value to Scintilla's Text: `scintilla.Text = string.Concat(scintilla.Lines.Select(f => f.Text));`. Sorry...
